### ISSUE TITLE
Check if member bug

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#781]
This is the error you get when running it in DBM 2.0

Action 4 is shown in the image below.
It was working on DiscordJS V12.2.0
Can it be the anchor part of it being an issue?

Error with the command "Check If Member", Action #4:
3|nt-canary2  | TypeError: this.dest is not a function
3|nt-canary2  |     at Object.action [as Check If Member] (/home/dashboard.newstargeted.com/public_html/nt3/actions/check_if_member_MOD.js:136:23)
3|nt-canary2  |     at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt3/bot.js:1115:21)
3|nt-canary2  |     at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt3/actions/action_list_comment_MOD.js:24:10)
3|nt-canary2  |     at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt3/bot.js:1115:21)
3|nt-canary2  |     at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt3/actions/action_list_comment_MOD.js:24:10)
3|nt-canary2  |     at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt3/bot.js:1115:21)
3|nt-canary2  |     at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt3/actions/action_list_comment_MOD.js:24:10)
3|nt-canary2  |     at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt3/bot.js:1115:21)
3|nt-canary2  |     at Object.Actions.invokeInteraction (/home/dashboard.newstargeted.com/public_html/nt3/bot.js:1085:10)
3|nt-canary2  |     at Object.Actions.preformActionsFromInteraction (/home/dashboard.newstargeted.com/public_html/nt3/bot.js:954:12)

![image](https://user-images.githubusercontent.com/4199669/137368924-916b836e-a9ce-4f4a-98d6-9d5586a3c5e2.png)

**Comment by RediPanda** [comment]
Yeah, I believe we don't use the dist() function in the new client file, hence it's spitting out errors.
I'll make a PR to amend it.
